imports:
    - { resource: config_dev.yml }

fos_elastica:
    clients:
        default: { host: localhost, port: 9250 }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

knp_rad:
    mailer:
        logger: true
    listener:
        exception_rethrow: true
